language: python
python:
  - 3.5
  - 3.6
  - 3.7-dev
install:
  - pip install poetry
  - poetry install
script:
  - poetry run isort --check-only --diff || exit 1
  - if [ $TRAVIS_PYTHON_VERSION != "3.5" ]; then poetry run black --check; fi
  - poetry run flake8
  - poetry run pytest
