language: python
python:
  - 3.5
  - 3.6
  - 3.7-dev
install:
  - pip install -r requirements.txt
  - python setup.py develop
  - if [ $TRAVIS_PYTHON_VERSION != "3.5" ]; then pip install black; fi
script:
  - isort --check-only --diff || exit 1
  - if [ $TRAVIS_PYTHON_VERSION != "3.5" ]; then black --check; fi
  - flake8
  - pytest
