[tool.black]
exclude = '''
/(
    \.git
  | \.pytest_cache
  | \.tox
  | \.venv
  | \.vscode
  | __pycache__
  | build
  | coverage
  | dist
)/
'''

[tool.pytest.ini_options]
testpaths = ["tests"]

[tool.isort]
default_section = "THIRDPARTY"
known_first_party = ["city_scrapers_core"]
skip_glob = [
    "*/.venv/*",
    "*/docs/*",
]
sections = [
  "FUTURE",
  "STDLIB",
  "THIRDPARTY",
  "FIRSTPARTY",
  "LOCALFOLDER",
]
multi_line_output = 3
line_length = 88
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
